<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Project Generator</title>
</head>

<body>
  <link href="../vendor/components/bootstrap/css/bootstrap.min.css" rel="stylesheet"/>
  <script src="../vendor/components/jquery/jquery.min.js"></script>
  <script src="../vendor/components/bootstrap/js/bootstrap.min.js"></script>

  <div class="container">
    <div class="row">
      <h1>Página não encontrada</h1>
    </div>
  </div>
</body>
</html>
