<!DOCTYPE html>
<html lang="pt-br">
    <head>
    
        <meta charset="utf-8">

    </head>

    <body>

        <link href="../../vendor/components/bootstrap/css/bootstrap.min.css" rel="stylesheet"/>
        <script src="../../vendor/components/jquery/jquery.min.js"></script>
        <script src="../../vendor/components/bootstrap/js/bootstrap.min.js"></script>

        <?php require_once __DIR__ . "/header.phtml" ?>

        <?php $this->conteudoView() ?>

        <?php require_once __DIR__ . "/footer.phtml" ?>

    </body>
</html>